#!/bin/bash

BUILDDIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/src/library/twitter/bootstrap/"
TARGET="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/src/"

cd $BUILDDIR

cp "${TARGET}config/bootstrap.less" "${BUILDDIR}less/variables.less"

make -B build bootstrap

cp ${BUILDDIR}bootstrap/css/*.css "${TARGET}htdocs/styles"
cp ${BUILDDIR}bootstrap/img/*.png "${TARGET}htdocs/images/"
cp ${BUILDDIR}bootstrap/js/*.js "${TARGET}htdocs/scripts/vendor/bootstrap/"
